In [1]:
import numpy as np

In [2]:
a=np.array([[20,39]])
b=np.array([[45,99]])

In [3]:
a.T+b.T

array([[ 65],
       [138]])

In [4]:
(a+b).T # Transposing a matrix

array([[ 65],
       [138]])

In [5]:
a*b# Matrix multiplication

array([[ 900, 3861]])

In [6]:
2*a# scalar multiplication

array([[40, 78]])

In [7]:
u=np.array([10,20])
v=np.array([4,5])
np.dot(u,v)# Dot product = 10*4 + 20*5

140

In [8]:
# matrix and vector multiplication
a=[[10,20],[15,30],[5,10]]
b=[5,10]
np.dot(a,b)

array([250, 375, 125])

In [9]:
a=[[10,20],[15,30],[5,10]]
b=[[11,6],[20,1]]
np.dot(a,b)

array([[510,  80],
       [765, 120],
       [255,  40]])

In [10]:
# PRINTING IDENTITY MATRICES OF SIZE N
I1=np.eye(3)
I2=np.eye(5)
print(I1,end=" = I1\n\n")
print(I2,end=" = I2\n\n")

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] = I1

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] = I2



In [11]:
# Inversing a matrix
# Note : all matrices don't have a inverse matrix hence the function will give an error for these type of matrices
a=np.array([
    [2,1,0],
    [0,1,0],
    [1,2,1],
])
b=np.linalg.inv(a)
print(a,end=' = a\n\n ')
print(b,end=' = |a|\n\n')

[[2 1 0]
 [0 1 0]
 [1 2 1]] = a

 [[ 0.5 -0.5  0. ]
 [ 0.   1.   0. ]
 [-0.5 -1.5  1. ]] = |a|



In [12]:
print(a*b)

[[ 1.  -0.5  0. ]
 [ 0.   1.   0. ]
 [-0.5 -3.   1. ]]
