# Numpy sample

In [1]:
import numpy as np

In [2]:
myarr=np.array([3,4,2,7],np.int8) # here np.datatype signifies the data type with the max no bits

In [3]:
myarr

array([3, 4, 2, 7], dtype=int8)

In [4]:
#There are 5 ways to create numpy arrays
#Conversion from other structures|

In [5]:
listarrays=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
listarrays.size

9

In [7]:

listarrays.dtype

dtype('int32')

In [8]:
listarrays.shape

(3, 3)

In [9]:
listarrays

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# Array creation using other methods 

In [11]:
zeros=np.zeros((3,6)) 
# Will create a double dimensional array filled with zeros

In [12]:
zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
singzero=np.zeros(4)
# Creates a single dimensional array filled with zeros

In [14]:
singzero

array([0., 0., 0., 0.])

In [15]:
rng=np.arange(12)
# Will return an array ranging from 0 to n-1 numbers

In [16]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
lspace=np.linspace(1,6,10)
# Will return an array between 1 and 6 with each element have 
# 10 bits of space between them including the decimal point
# If zero is passed then it will return an empty array

In [18]:
lspace

array([1.        , 1.55555556, 2.11111111, 2.66666667, 3.22222222,
       3.77777778, 4.33333333, 4.88888889, 5.44444444, 6.        ])

In [19]:
emp=np.empty((4,3))
# Will return an array of 4,3 size with garbage value in it.

In [20]:
emp

array([[1.25575129e-311, 2.81617418e-322, 0.00000000e+000],
       [0.00000000e+000, 1.11260619e-306, 8.75983079e+164],
       [5.44909749e-090, 1.59955846e+160, 8.26774178e-072],
       [1.39444004e-047, 6.48224659e+170, 4.93432906e+257]])

In [21]:
emp_like=np.empty_like(lspace)
# Will return an array of size equal to the one passed inside the function
# This is used to save space space as unlike in c/c++ , python does not have pointers to allocate the memory

In [22]:
emp_like

array([1.25575129e-311, 2.81617418e-322, 1.11260619e-306, 8.75983079e+164,
       5.44909749e-090, 1.59955846e+160, 8.26774178e-072, 1.39444004e-047,
       6.48224659e+170, 4.93432906e+257])

In [23]:
ide=np.identity(4)
# returns an identity array

In [24]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
arr=np.arange(9)

In [26]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
arr=arr.reshape((3,3))
# returns a new reshaped array not affecting the original array
# resphape will only work if the number of elements is completely divisible by the row passed

In [28]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
arr.ravel()
# Used to return the linear size of the array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
arr.shape # proof that .reshape does not affect the actual size of the array

(3, 3)

In [31]:
l1=[[2,3,1],
   [4,6,4],
   [7,8,9]]

In [32]:
ar=np.array(l1)

In [33]:
ar

array([[2, 3, 1],
       [4, 6, 4],
       [7, 8, 9]])

In [34]:
# Axes are the direction along the rows and colomns
# axis 0 is from the top to bottom
# axis 1 is from left to right

In [35]:
ar.sum(axis=0) # This will return the sum of each colomn in the form of another array

array([13, 17, 14])

In [36]:
ar.sum(axis=1) # This will return the sum of each row in the form of another array|

array([ 6, 14, 24])

In [37]:
ar.T # returns a transposed array

array([[2, 4, 7],
       [3, 6, 8],
       [1, 4, 9]])

In [38]:
ar

array([[2, 3, 1],
       [4, 6, 4],
       [7, 8, 9]])

In [39]:
ar.flat # returns a 1D iterable item

In [40]:
for i in ar.flat:
    print(i)

2
3
1
4
6
4
7
8
9


In [41]:
ar.ndim

2

In [42]:
arr.ndim

2

In [43]:
l1=[5,9,2,6,8,4,1,7,3]
newar=np.array(l1)

In [44]:
newar.ndim

1

In [45]:
# Returns the number of dimensions of the structure

In [46]:
newar.nbytes # returns the number of byter occupied by the array

36

In [47]:
newar.argmax()

1

In [48]:
newar.argmin() 

6

In [49]:
newar.argsort()

array([6, 2, 8, 5, 0, 3, 7, 4, 1], dtype=int64)

In [50]:
# argmethods returns the indices of the all mentioned functions
# ex : argsort returns the indices of the numbers in its sorted positions

In [51]:
ar.argmax(axis=0) # returns the position of the max element in each colomn (axis=0)

array([2, 2, 2], dtype=int64)

In [52]:
ar.argmax(axis=1) # returns the position of the min element in each row (axis=1)

array([1, 1, 2], dtype=int64)

In [53]:
ar.argsort(axis=1) # returns the position of each element if it were in the sorted position in each row

array([[2, 0, 1],
       [0, 2, 1],
       [0, 1, 2]], dtype=int64)

In [54]:
ar.argsort(axis=0) # returns the position of each element if it were in the sorted position in each colomn

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [55]:
ar

array([[2, 3, 1],
       [4, 6, 4],
       [7, 8, 9]])

In [56]:
ar2=np.array([[12, 3, 5],
       [2, 1, 4],
       [3, 8, 5]])

In [57]:
ar
ar2

array([[12,  3,  5],
       [ 2,  1,  4],
       [ 3,  8,  5]])

In [58]:
ar+ar2

array([[14,  6,  6],
       [ 6,  7,  8],
       [10, 16, 14]])

In [59]:
ar*ar2 # multiplies each element of ar with its corresponding position in ar2

array([[24,  9,  5],
       [ 8,  6, 16],
       [21, 64, 45]])

In [60]:
# returns the values instead of the indices
print(ar2.max())
print(ar2.min())

12
1


In [61]:
ar2

array([[12,  3,  5],
       [ 2,  1,  4],
       [ 3,  8,  5]])

In [62]:
np.where(ar2>=5) # returns a tuple of x and y(the indices of each position)

(array([0, 0, 2, 2], dtype=int64), array([0, 2, 1, 2], dtype=int64))

In [63]:
np.count_nonzero(ar2)

9

In [64]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [65]:
import sys

In [66]:
py_ar=[1,2,3]
np_ar=np.array(py_ar)

In [67]:
sys.getsizeof(1) * len(py_ar) # size of normal py_ar list

84

In [68]:
np_ar.itemsize * np_ar.size # size of array using numpy

12

In [69]:
# The difference is substantial over here with a whopping 72 bytes difference